CONTIKI_PROJECT = hello-world
all: $(CONTIKI_PROJECT)

# MODULES += os/services/shell

AT86RF2XX_BOARD = ISMTV_v1.1
TARGET=vesna
RADIO = AT86RF21X

CONTIKI = ../..
include $(CONTIKI)/Makefile.include
