CONTIKI_PROJECT = client
all: $(CONTIKI_PROJECT)

MAKE_MAC = MAKE_MAC_TSCH

AT86RF2XX_BOARD = ISMTV_v1.1
TARGET=vesna

MODULES += os/services/shell

VESNA= ../../arch/platform/vesna/vesna-drivers/


CONTIKI = ../..
include $(CONTIKI)/Makefile.include
