CONTIKI_PROJECT = hello-world
all: $(CONTIKI_PROJECT)

# MAKE_MAC = MAKE_MAC_TSCH
# MODULES += os/services/shell

AT86RF2XX_BOARD = ISMTV_v1.1
TARGET=vesna

CONTIKI = ../..
include $(CONTIKI)/Makefile.include
